import { Cpu, Database, ScrollText, ShieldAlert, Sparkles } from 'lucide-react';
import type { ReplySource } from '../types';

const LOOKUP: Record<
	ReplySource,
	{ label: string; title: string; icon: typeof Cpu; className: string }
> = {
	guard: {
		label: 'Stopped before the model',
		title: 'This question was answered without consulting the model at all.',
		icon: ShieldAlert,
		className: 'gracieSource--guard',
	},
	data: {
		label: 'From your saved progress',
		title: 'Read straight from your own stored progress — no model involved.',
		icon: Database,
		className: 'gracieSource--data',
	},
	blended: {
		label: 'Your data + on-device wording',
		title: 'The numbers come from your saved progress; only the closing line was written on this device.',
		icon: Sparkles,
		className: 'gracieSource--blended',
	},
	model: {
		label: 'Written on this device',
		title: 'Generated by the model running in this browser tab. Nothing was sent to a server.',
		icon: Cpu,
		className: 'gracieSource--model',
	},
	scripted: {
		label: 'Scripted reply',
		title: 'Robot mode — a written-in-advance reply, with no model involved.',
		icon: ScrollText,
		className: 'gracieSource--scripted',
	},
};

/**
 * Says where a reply came from.
 *
 * Shown on every turn on purpose: "the model wrote this" and "your own saved
 * data says this" are very different claims, and a learner should be able to
 * tell them apart at a glance.
 */
export default function SourceBadge({ source }: { source: ReplySource }) {
	const { label, title, icon: Icon, className } = LOOKUP[source];
	return (
		<span className={`gracieSource ${className}`} title={title}>
			<Icon className="size-3" aria-hidden="true" />
			{label}
		</span>
	);
}
